<a href="https://colab.research.google.com/github/mszhdgr/Machine_learning/blob/Main/Linear%20Regression/India_house_prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings

warnings.filterwarnings("ignore")

In [4]:
import kagglehub

path = kagglehub.dataset_download("sukhmandeepsinghbrar/house-prices-india")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'house-prices-india' dataset.
Path to dataset files: /kaggle/input/house-prices-india

In [5]:
import pandas as pd

df = pd.read_csv("/kaggle/input/house-prices-india/House Price India.csv")
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [6]:
df.describe()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,1.461900e+04,14619.000000,14619.000000,14619.000000,14619.000000,1.461900e+04,14619.000000,14619.000000,14619.000000,14619.000000,...,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,1.461900e+04
mean,6.762821e+09,42604.546412,3.379233,2.129557,2098.156851,1.509369e+04,1.502326,0.007661,0.232848,3.430399,...,1970.929817,90.930228,122033.064300,52.792843,-114.403996,1996.641836,12754.003078,2.012244,64.951433,5.388063e+05
std,6.237162e+03,67.343747,0.938655,0.769955,928.218740,3.792089e+04,0.540241,0.087196,0.765651,0.664047,...,29.491743,416.230218,19.081451,0.137525,0.141325,691.078387,26059.234785,0.817312,8.936129,3.672294e+05
min,6.762810e+09,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,42546.000000,3.000000,1.750000,1440.000000,5.010500e+03,1.000000,0.000000,0.000000,3.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.500000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

In [7]:
df.isna().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [8]:
df.columns

Index(['id', 'Date', 'number of bedrooms', 'number of bathrooms',
       'living area', 'lot area', 'number of floors', 'waterfront present',
       'number of views', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

In [9]:
columns = ['number of bedrooms', 'number of bathrooms','condition of the house','Number of schools nearby', 'Distance from the airport']
features = pd.DataFrame(df, columns=columns)
features.head()

,number of bedrooms,number of bathrooms,condition of the house,Number of schools nearby,Distance from the airport
0,4,2.50,5,2,51
1,5,2.75,3,1,53
2,4,2.50,3,3,76
3,3,2.00,4,1,51
4,3,2.50,4,1,67

In [10]:
features.describe()

,number of bedrooms,number of bathrooms,condition of the house,Number of schools nearby,Distance from the airport
count,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000
mean,3.379233,2.129557,3.430399,2.012244,64.951433
std,0.938655,0.769955,0.664047,0.817312,8.936129
min,1.000000,0.500000,1.000000,1.000000,50.000000
25%,3.000000,1.750000,3.000000,1.000000,57.000000
50%,3.000000,2.250000,3.000000,2.000000,65.000000
75%,4.000000,2.500000,4.000000,3.000000,73.000000
max,33.000000,8.000000,5.000000,3.000000,80.000000

In [11]:
labels = pd.DataFrame(df, columns=['Price'])
labels.head()

     Price
0  1400000
1  1200000
2   838000
3   805000
4   790000

In [12]:
len(features)

14619

In [13]:
y = labels.values.ravel()
y

array([1400000, 1200000,  838000, ...,  209000,  205000,  146000])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, y, test_size=0.3)

In [15]:
len(X_train), len(X_test)

(10233, 4386)

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.decomposition import  PCA

In [34]:
ct = Pipeline(
    steps=[
        ('pca', PCA(2)),
        ('lr_model', LinearRegression())
    ]
)

In [35]:
ct.fit(X_train, y_train)

Pipeline(steps=[('pca', PCA(n_components=2)), ('lr_model', LinearRegression())])

In [36]:
ct.named_steps

{'pca': PCA(n_components=2), 'lr_model': LinearRegression()}

In [37]:
ct.score(X_test,y_test)

0.2046344175614737

In [38]:
ct.feature_names_in_

array(['number of bedrooms', 'number of bathrooms',
       'condition of the house', 'Number of schools nearby',
       'Distance from the airport'], dtype=object)

In [39]:
import numpy as np

valz = np.array([1, 1, 2, 1, 300])
pred = ct.predict(valz.reshape(1, -1))
pred

array([91024.70706158])

In [41]:
valz2 = np.array([4, 5, 4, 4, 70])
pred2 = ct.predict(valz2.reshape(1, -1))
pred2

array([856074.77256087])