<a href="https://colab.research.google.com/github/mszhdgr/Machine_learning/blob/Main/Linear%20Regression/Texas_Residential_Real_Estate_Intelligence_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jahnavikachhia23/texas-residential-real-estate-intelligence-2026")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'texas-residential-real-estate-intelligence-2026' dataset.
Path to dataset files: /kaggle/input/texas-residential-real-estate-intelligence-2026

In [10]:
import pandas as pd

df = pd.read_csv("/kaggle/input/texas-residential-real-estate-intelligence-2026/Texas_Residential_Real Estate_Intelligenc_ 2026.csv")
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,Price_Per_SqFt
0,single_family,NaN,Experience The Best Of North Texas Living In T...,499000.0,2040.0,2.0,3.0,3.0,2.0,2.0,2.0,2021.0,244.61
1,single_family,NaN,"Welcome home to [Redacted Entity], [Redacted E...",494500.0,3674.0,2.0,6.0,4.0,3.0,3.0,NaN,2025.0,134.59
2,single_family,NaN,Welcome to this beautiful home located in [Red...,229000.0,1650.0,2.0,3.0,3.0,2.0,2.0,2.0,2020.0,138.79
3,single_family,NaN,"Welcome to [Redacted Entity] - where style, co...",260000.0,1741.0,1.0,3.0,2.0,2.0,2.0,2.0,2005.0,149.34
4,single_family,single family detached,***READY NOW*** Discover this stunning new con...,334990.0,2255.0,2.0,4.0,4.0,3.0,3.0,2.0,2025.0,148.55

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12137 entries, 0 to 12136
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             12137 non-null  object
 1   sub_type         1749 non-null   object
 2   text             12137 non-null  object
 3   listPrice        12134 non-null  float64
 4   sqft             12073 non-null  float64
 5   stories          11630 non-null  float64
 6   beds             12009 non-null  float64
 7   baths            11863 non-null  float64
 8   baths_full       11988 non-null  float64
 9   baths_full_calc  11991 non-null  float64
 10  garage           10224 non-null  float64
 11  year_built       9849 non-null   float64
 12  Price_Per_SqFt   12135 non-null  float64
dtypes: float64(10), object(3)
memory usage: 1.2+ MB

In [12]:
df.describe()

,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,Price_Per_SqFt
count,1.213400e+04,12073.000000,11630.000000,12009.000000,11863.000000,11988.000000,11991.000000,10224.000000,9849.000000,12135.000000
mean,4.998792e+05,2286.140230,1.442562,3.611791,2.882660,2.475142,2.480527,2.134390,2013.043050,208.948589
std,5.409439e+05,1048.659141,0.549794,1.014476,1.191023,0.917721,0.915769,0.605927,22.132438,139.697072
min,8.500000e+02,240.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1654.000000,0.000000
25%,2.880922e+05,1640.000000,1.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2015.000000,154.915000
50%,3.749000e+05,2085.000000,1.000000,4.000000,3.000000,2.000000,2.000000,2.000000,2023.000000,182.910000
75%,5.390000e+05,2686.000000,2.000000,4.000000,3.000000,3.000000,3.000000,2.000000,2025.000000,220.840000
max,1.199500e+07,19600.000000,7.000000,29.000000,39.000000,26.000000,26.000000,20.000000,2028.000000,6363.980000

In [13]:
df.isna().sum()

type                   0
sub_type           10388
text                   0
listPrice              3
sqft                  64
stories              507
beds                 128
baths                274
baths_full           149
baths_full_calc      146
garage              1913
year_built          2288
Price_Per_SqFt         2
dtype: int64

In [14]:
df.dropna(inplace=True)

In [15]:
df.isna().sum()

type               0
sub_type           0
text               0
listPrice          0
sqft               0
stories            0
beds               0
baths              0
baths_full         0
baths_full_calc    0
garage             0
year_built         0
Price_Per_SqFt     0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1284 entries, 4 to 12113
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             1284 non-null   object
 1   sub_type         1284 non-null   object
 2   text             1284 non-null   object
 3   listPrice        1284 non-null   float64
 4   sqft             1284 non-null   float64
 5   stories          1284 non-null   float64
 6   beds             1284 non-null   float64
 7   baths            1284 non-null   float64
 8   baths_full       1284 non-null   float64
 9   baths_full_calc  1284 non-null   float64
 10  garage           1284 non-null   float64
 11  year_built       1284 non-null   float64
 12  Price_Per_SqFt   1284 non-null   float64
dtypes: float64(10), object(3)
memory usage: 140.4+ KB

In [17]:
df.head(3)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,Price_Per_SqFt
4,single_family,single family detached,***READY NOW*** Discover this stunning new con...,334990.0,2255.0,2.0,4.0,4.0,3.0,3.0,2.0,2025.0,148.55
35,single_family,single family detached,WELCOME to this lovely single story home that ...,179900.0,988.0,1.0,3.0,1.0,1.0,1.0,1.0,1982.0,182.09
39,single_family,single family detached,BUYER WAS GETTING ONE HECK OF A DEAL.. STILL B...,320000.0,2250.0,2.0,3.0,3.0,2.0,2.0,2.0,2022.0,142.22

In [18]:
features = df.drop(columns=['type','sub_type','text','listPrice'])
features.head()

,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,Price_Per_SqFt
4,2255.0,2.0,4.0,4.0,3.0,3.0,2.0,2025.0,148.55
35,988.0,1.0,3.0,1.0,1.0,1.0,1.0,1982.0,182.09
39,2250.0,2.0,3.0,3.0,2.0,2.0,2.0,2022.0,142.22
52,1916.0,1.0,3.0,3.0,2.0,2.0,2.0,2025.0,208.24
57,2368.0,1.0,4.0,3.0,3.0,3.0,2.0,2025.0,137.67

In [19]:
label = pd.DataFrame(df, columns=['listPrice'])
label

       listPrice
4       334990.0
35      179900.0
39      320000.0
52      398990.0
57      325999.0
...          ...
12094   299000.0
12104   798000.0
12109   525000.0
12111   997900.0
12113   349000.0

[1284 rows x 1 columns]

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

In [21]:
scaled_features

array([[ 0.2151742 ,  0.66499764,  0.6475293 , ...,  0.0232784 ,
         0.47709992, -0.47566509],
       [-1.47642662, -0.93099669, -0.56623365, ..., -1.33533386,
        -2.3731101 , -0.23227066],
       [ 0.20849859,  0.66499764, -0.56623365, ...,  0.0232784 ,
         0.27824806, -0.52160089],
       ...,
       [-0.20805978,  0.66499764, -0.56623365, ...,  0.0232784 ,
         0.01311225,  0.41220933],
       [ 1.98154191,  0.66499764,  1.86129224, ...,  1.38189066,
         0.47709992,  0.47026405],
       [-1.42435683, -0.93099669, -2.99375954, ..., -1.33533386,
        -1.31256683,  0.91235077]])

In [24]:
y = label.values.ravel()
y

array([334990., 179900., 320000., ..., 525000., 997900., 349000.])

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(scaled_features, y, test_size=0.2)
len(X_train), len(X_test)

(1027, 257)

In [26]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [27]:
accuracy = model.score(X_test,y_test)
accuracy

0.8847375278931007

In [28]:
from sklearn.metrics import r2_score

pred = model.predict(X_test)
r2 = r2_score(y_test, pred)
r2

0.8847375278931007

In [41]:
features.columns

Index(['sqft', 'stories', 'beds', 'baths', 'baths_full', 'baths_full_calc',
       'garage', 'year_built', 'Price_Per_SqFt'],
      dtype='object')

In [43]:
test_data = [[200, 2, 1, 1, 0, 0, 0, 1990, 300]]
test_df = pd.DataFrame(test_data, columns=features.columns)
test_df

,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,Price_Per_SqFt
0,200,2,1,1,0,0,0,1990,300

In [44]:
test_scaled = scaler.transform(test_df)

In [45]:
test_scaled

array([[-2.52850354,  0.66499764, -2.99375954, -2.01796001, -3.53014527,
        -3.53014527, -2.69394611, -1.84283846,  0.62338338]])

In [46]:
pred = model.predict(test_scaled)

In [49]:
print(pred.item())

71201.40050149994